name: CI/CD Pipeline
on: [push]

jobs:
  flutter-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          cd app
          flutter pub get
          flutter test

  ml-training:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          cd ai-ml\crowd_prediction
          pip install -r requirements.txt
          python train_model.py